service:
  name: todolist

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2

functions:
  createTodo:
    handler: src/functions/createTodo.handle
    events:
      - http:
          path: /todo
          method: POST
          cors: true
  listTodoByUserId:
    handler: src/functions/listTodoByUserId.handle
    events:
      - http:
          path: /todo/{user_id}
          method: GET
          cors: true

resources:
  Resources:
    certificateUsersDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 4
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH